### ISSUE TITLE
Paths are wrong in aggregate reports.

### ISSUE THREAD

**Issue by hrj** [scoverage/sbt-scoverage#93]
In the aggregate report, the path for an individual file's report, is wrong:

It should be: `project/subproject/target/scala-2.11/package/file.scala.html`

But it ends up being: `project/subproject/src/main/scala/package/file.scala.html`

**Comment by hrj** [comment]
Digging deeper, I noticed something else:

There is directory tree under `target/scala-2.11/scoverage-report` which mimics the absolute path of the project. For example, if the scala project was in this directory: `/home/user/myproject` then the directory created is `/home/user/myproject/target/scala-2.11/scoverage-report/home/user/myproject/subproject/src/main/scala/package/file.scala.html`. Phew!

So, the link in the aggregate coverage report has mixed different paths together.

Aside, I would suggest not using the absolute path in the report, since it leaks information not related to the project, when I am sharing the report to someone. For example, if I checkout a project under `/home/hrj/junk/project` or under `/clientX/proj`, the one who sees the report knows how well I respect the project or which client I work for, etc.

**Comment by gslowikowski** [comment]
https://github.com/scoverage/scalac-scoverage-plugin/pull/109 + https://github.com/scoverage/sbt-scoverage/pull/98 should fix this issue

**Comment by VladUreche** [comment]
FYI, I also bumped into this. Another problem was that if I run `coverageAggregate` before running `coverageReport` for all projects, `sbt-scoverage` loses all coverage data and shows `0% covered`.

**Comment by VladUreche** [comment]
Possibly related: #69.

**Comment by gslowikowski** [comment]
Try `1.0.5-SNAPSHOT` version please, add:
```scala
resolvers ++= Seq( Classpaths.sbtPluginSnapshots, Resolver.sonatypeRepo("snapshots") )

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.0.5-SNAPSHOT")
```
to your `project/plugins.sbt` file.

**Comment by VladUreche** [comment]
@gslowikowski Thanks! Linking works fine, but I still get `0.00%` for the coverage everywhere.

**Comment by VladUreche** [comment]
To reproduce the problem, here's what I do:
```
$ git checkout https://github.com/miniboxing/miniboxing-plugin.git
$ cd miniboxing-plugin
$ git checkout sbt-scoverage-snapshot
$ sbt
> clean
> coverage
> test
> coverageAggreagate
> coverageReport
> coverageAggreagate
```
The first `coverageAggregate` shows `0.00% coverage` everywhere. The second `coverageAggregate` shows the correct coverage. I would expect it to show the correct coverage the first time, without requiring me to go through `coverageReport`.

**Comment by gslowikowski** [comment]
Are you testing on `miniboxing-plugin`, `wip` branch? What SBT command do you execute?

**Comment by gslowikowski** [comment]
Thanks :)

**Comment by VladUreche** [comment]
@gslowikowski thank you for looking into it :)

**Comment by ckipp01** [comment]
I believe this should be fixed. If you still have an issue with the please do report back.
